//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MpegSplitter.rc
//
#define IDS_OPTIONS_CAPTION             14135
#define IDS_MPEGSPLITTER_FSTREAM_CHANGE 41120
#define IDS_MPEGSPLITTER_LANG_ORDER     41121
#define IDS_MPEGSPLITTER_SUB_ORDER      41122
#define IDS_MPEGSPLITTER_VC1_GUIDFLAG   41123
#define IDS_MPEGSPLITTER_SUB_FORCING    41124
#define IDS_MPEGSPLITTER_TRACKS_ORDER   41125
#define IDS_MPEGSPLITTER_TRUEHD_OUTPUT  41126
#define IDS_MPEGSPLITTER_THD_NOSPLIT    41127
#define IDS_MPEGSPLITTER_ALT_DUR_CALC   41128

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
