#if defined(__GNUC__)
/* used for inline assembly stuff with GCC syntax */
  #define HAVE_MMX 1
  #define ENABLE_MMX 1
  #define HAVE_SSSE3 1
  #define ENABLE_SSSE3 1

  #define ARCH_X86 1

  #ifdef ARCH_X86_64
    #define HAVE_FAST_64BIT 1
  #else
    #define ARCH_X86_32 1
  #endif
#else
	#define ENABLE_MMX 0
	#define ENABLE_SSSE3 0
#endif


#define HAVE_MALLOC_H 1
#define HAVE_LRINTF 1
#define SIMPLE_IDCT 1
#define HAVE_W32THREADS 1
#define HAVE_THREADS 1
#define HAVE_MEMALIGN 1

#define ASMALIGN(ZEROBITS) ".align 1<<" #ZEROBITS "\n\t"

#define HAVE_BSWAP 1
#define ENABLE_BSWAP 1


#define CONFIG_DECODERS 1
#define ENABLE_DECODERS 1

#define ENABLE_ENCODERS 0

#define CONFIG_GPL 1
#define ENABLE_GPL 1

#define CONFIG_ZLIB 1
#define ENABLE_ZLIB 1

#define ENABLE_SMALL 0

#define ENABLE_GRAY 1


#define ENABLE_AASC_DECODER 0
#define CONFIG_AMV_DECODER 1
#define ENABLE_AMV_DECODER 1
#define ENABLE_ASV1_DECODER 0
#define ENABLE_ASV2_DECODER 0
#define ENABLE_AVS_DECODER 0
#define ENABLE_CAVS_DECODER 0
#define ENABLE_CINEPAK_DECODER 0
#define ENABLE_CSCD_DECODER 0
#define ENABLE_CYUV_DECODER 0
#define ENABLE_DVVIDEO_DECODER 0
#define ENABLE_EIGHTBPS_DECODER 0
#define ENABLE_FFV1_DECODER 0
#define ENABLE_FFVHUFF_DECODER 0
#define CONFIG_FLV_DECODER 1
#define ENABLE_FLV_DECODER 1
#define ENABLE_FRAPS_DECODER 0
#define ENABLE_H261_DECODER 0
#define CONFIG_H263_DECODER 1
#define ENABLE_H263_DECODER 1
#define CONFIG_H263I_DECODER 1
#define ENABLE_H263I_DECODER 1
#define CONFIG_H264_DECODER 1
#define ENABLE_H264_DECODER 1
#define ENABLE_HUFFYUV_DECODER 0
#define ENABLE_INDEO2_DECODER 0
#define ENABLE_INDEO3_DECODER 0
#define ENABLE_JPEGLS_DECODER 0
#define ENABLE_LOCO_DECODER 0
#define ENABLE_MJPEG_DECODER 0
#define ENABLE_MJPEGB_DECODER 0
#define ENABLE_MPEG1VIDEO_DECODER 0
#define ENABLE_MPEG2VIDEO_DECODER 0
#define CONFIG_MPEG4_DECODER 1
#define ENABLE_MPEG4_DECODER 1
#define ENABLE_MPEGVIDEO_DECODER 0
#define CONFIG_MSMPEG4V1_DECODER 1
#define ENABLE_MSMPEG4V1_DECODER 1
#define CONFIG_MSMPEG4V2_DECODER 1
#define ENABLE_MSMPEG4V2_DECODER 1
#define CONFIG_MSMPEG4V3_DECODER 1
#define ENABLE_MSMPEG4V3_DECODER 1
#define ENABLE_MSRLE_DECODER 0
#define ENABLE_MSVIDEO1_DECODER 0
#define ENABLE_MSZH_DECODER 0
#define ENABLE_PNG_DECODER 0
#define ENABLE_QPEG_DECODER 0
#define ENABLE_QTRLE_DECODER 0
#define ENABLE_RPZA_DECODER 0
#define ENABLE_RV10_DECODER 0
#define ENABLE_RV20_DECODER 0
#define ENABLE_SNOW_DECODER 0
#define CONFIG_SP5X_DECODER 1
#define ENABLE_SP5X_DECODER 1
#define CONFIG_SVQ1_DECODER 1
#define ENABLE_SVQ1_DECODER 1
#define CONFIG_SVQ3_DECODER 1
#define ENABLE_SVQ3_DECODER 1
#define CONFIG_THEORA_DECODER 1
#define ENABLE_THEORA_DECODER 1
#define ENABLE_TRUEMOTION1_DECODER 0
#define ENABLE_TRUEMOTION2_DECODER 0
#define ENABLE_TSCC_DECODER 0
#define ENABLE_ULTI_DECODER 0
#define CONFIG_VC1_DECODER 1
#define ENABLE_VC1_DECODER 1
#define ENABLE_VCR1_DECODER 0
#define ENABLE_VP3_DECODER 0
#define CONFIG_VP5_DECODER 1
#define ENABLE_VP5_DECODER 1
#define CONFIG_VP6_DECODER 1
#define ENABLE_VP6_DECODER 1
#define CONFIG_VP6A_DECODER 1
#define ENABLE_VP6A_DECODER 1
#define CONFIG_VP6F_DECODER 1
#define ENABLE_VP6F_DECODER 1
#define CONFIG_WMV1_DECODER 1
#define ENABLE_WMV1_DECODER 1
#define CONFIG_WMV2_DECODER 1
#define ENABLE_WMV2_DECODER 1
#define CONFIG_WMV3_DECODER 1
#define ENABLE_WMV3_DECODER 1
#define CONFIG_WNV1_DECODER 1
#define ENABLE_WNV1_DECODER 1
#define ENABLE_XL_DECODER 0
#define ENABLE_ZLIB_DECODER 0
#define ENABLE_ZMBV_DECODER 0

#define ENABLE_ATRAC3_DECODER 0
#define ENABLE_COOK_DECODER 0
#define ENABLE_IMC_DECODER 0
#define ENABLE_MACE3_DECODER 0
#define ENABLE_MACE6_DECODER 0
#define ENABLE_NELLYMOSER_DECODER 0
#define ENABLE_QDM2_DECODER 0
#define ENABLE_RA_144_DECODER 0
#define ENABLE_RA_288_DECODER 0
#define ENABLE_TRUESPEECH_DECODER 0
#define ENABLE_TTA_DECODER 0
#define ENABLE_VORBIS_DECODER 0
#define ENABLE_WMAV1_DECODER 0
#define ENABLE_WMAV2_DECODER 0
#define ENABLE_PCM_ALAW_DECODER 0
#define ENABLE_PCM_MULAW_DECODER 0
#define ENABLE_ADPCM_4XM_DECODER 0
#define ENABLE_ADPCM_ADX_DECODER 0
#define ENABLE_ADPCM_CT_DECODER 0
#define ENABLE_ADPCM_EA_DECODER 0
#define ENABLE_ADPCM_G726_DECODER 0
#define ENABLE_ADPCM_IMA_AMV_DECODER 0
#define ENABLE_ADPCM_IMA_DK3_DECODER 0
#define ENABLE_ADPCM_IMA_DK4_DECODER 0
#define ENABLE_ADPCM_IMA_QT_DECODER 0
#define ENABLE_ADPCM_IMA_SMJPEG_DECODER 0
#define ENABLE_ADPCM_IMA_WAV_DECODER 0
#define ENABLE_ADPCM_IMA_WS_DECODER 0
#define ENABLE_ADPCM_MS_DECODER 0
#define ENABLE_ADPCM_SBPRO_2_DECODER 0
#define ENABLE_ADPCM_SBPRO_3_DECODER 0
#define ENABLE_ADPCM_SBPRO_4_DECODER 0
#define ENABLE_ADPCM_SWF_DECODER 0
#define ENABLE_ADPCM_XA_DECODER 0
#define ENABLE_ADPCM_YAMAHA_DECODER 0

#define ENABLE_DVVIDEO_ENCODER 0
#define ENABLE_FFV1_ENCODER 0
#define ENABLE_FFVHUFF_ENCODER 0
#define ENABLE_FLV_ENCODER 0
#define ENABLE_H261_ENCODER 0
#define ENABLE_H263_ENCODER 0
#define ENABLE_H263P_ENCODER 0
#define ENABLE_H264_ENCODER 0
#define ENABLE_HUFFYUV_ENCODER 0
#define ENABLE_LJPEG_ENCODER 0
#define ENABLE_MJPEG_ENCODER 0
#define ENABLE_MPEG1VIDEO_ENCODER 0
#define ENABLE_MPEG2VIDEO_ENCODER 0
#define ENABLE_MPEG4_ENCODER 0
#define ENABLE_MSMPEG4V1_ENCODER 0
#define ENABLE_MSMPEG4V2_ENCODER 0
#define ENABLE_MSMPEG4V3_ENCODER 0
#define ENABLE_PNG_ENCODER 0
#define ENABLE_RV10_ENCODER 0
#define ENABLE_RV20_ENCODER 0
#define ENABLE_SNOW_ENCODER 0
#define ENABLE_WMV1_ENCODER 0
#define ENABLE_WMV2_ENCODER 0
#define ENABLE_AC3_ENCODER 0


#define CONFIG_MPEGAUDIO_HP 1
#define ENABLE_MPEGAUDIO_HP 1


// LibAVFormat
#define CONFIG_DEMUXERS 1
#define CONFIG_AC3_DEMUXER 1


#define HAVE_7REGS 1
#define HAVE_EBX_AVAILABLE 1
